name: Build Windows Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.0)'
        required: false
        default: '1.0.0'
        type: string
      release_type:
        description: 'Release type'
        required: false
        default: 'draft'
        type: choice
        options:
        - draft
        - prerelease
        - release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Extract version from tag or input
        run: |
          if ("${{ github.event_name }}" -eq "workflow_dispatch") {
            $version = "${{ github.event.inputs.version }}"
            Write-Host "Using manual version: $version"
          } else {
            $tag = $env:GITHUB_REF -replace 'refs/tags/', ''
            $version = $tag -replace '^v', ''
            Write-Host "Using tag version: $version"
          }
          npm version $version --no-git-tag-version

      # 🔑 Restaurar certificado
      - name: Restore certificate
        run: |
          echo "${{ secrets.WINDOWS_CERTIFICATE }}" | base64 -d > certificate.p12

      - name: Build React app
        run: npm run build

      - name: Package and publish Electron app (offline config)
        run: npm run electron:build:offline:publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          CI: true

      - name: Create manual release
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.exe
          tag_name: v${{ github.event.inputs.version }}
          name: Release v${{ github.event.inputs.version }}
          draft: ${{ github.event.inputs.release_type == 'draft' }}
          prerelease: ${{ github.event.inputs.release_type == 'prerelease' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
